/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotifei.view;

import java.awt.Color;
import java.util.List;
import javax.swing.JTextField;
import spotifei.controller.MusicaController;
import spotifei.model.Musica;

/**
 *
 * @author adone
 */
public class BuscaMusicasPanel extends javax.swing.JPanel {

    private MusicaController controller;
    
    public BuscaMusicasPanel(MusicaController controller) {
        initComponents();
        this.controller = controller;
        controller.setView(this);
        controller.listarMusicas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperiorBusca = new javax.swing.JPanel();
        txtBuscarMusicas = new javax.swing.JTextField();
        btnBuscarMusicas = new javax.swing.JButton();
        pnlResultadosBusca = new javax.swing.JScrollPane();
        pnlListaMusicas = new javax.swing.JPanel();

        setBackground(new java.awt.Color(44, 44, 44));
        setMinimumSize(new java.awt.Dimension(850, 768));
        setPreferredSize(new java.awt.Dimension(850, 768));
        setLayout(new java.awt.BorderLayout());

        pnlSuperiorBusca.setBackground(new java.awt.Color(44, 44, 44));
        pnlSuperiorBusca.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 10));

        txtBuscarMusicas.setColumns(25);
        txtBuscarMusicas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBuscarMusicas.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscarMusicas.setText("Pesquisar...");
        txtBuscarMusicas.setToolTipText("");
        txtBuscarMusicas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBuscarMusicas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarMusicasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarMusicasFocusLost(evt);
            }
        });
        pnlSuperiorBusca.add(txtBuscarMusicas);

        btnBuscarMusicas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnBuscarMusicas.setText("Buscar");
        btnBuscarMusicas.setBorderPainted(false);
        btnBuscarMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMusicasActionPerformed(evt);
            }
        });
        pnlSuperiorBusca.add(btnBuscarMusicas);

        add(pnlSuperiorBusca, java.awt.BorderLayout.PAGE_START);

        pnlListaMusicas.setBackground(new java.awt.Color(55, 55, 55));
        pnlListaMusicas.setLayout(new javax.swing.BoxLayout(pnlListaMusicas, javax.swing.BoxLayout.Y_AXIS));
        pnlResultadosBusca.setViewportView(pnlListaMusicas);

        add(pnlResultadosBusca, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMusicasActionPerformed
        // TODO add your handling code here:
        controller.listarMusicas();
    }//GEN-LAST:event_btnBuscarMusicasActionPerformed

    private void txtBuscarMusicasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarMusicasFocusGained
        // TODO add your handling code here:
        if (txtBuscarMusicas.getText().equals("Pesquisar...")) {
            txtBuscarMusicas.setText("");
            txtBuscarMusicas.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtBuscarMusicasFocusGained

    private void txtBuscarMusicasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarMusicasFocusLost
        // TODO add your handling code here:
        if (txtBuscarMusicas.getText().equals("")) {
            txtBuscarMusicas.setText("Pesquisar...");
            txtBuscarMusicas.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtBuscarMusicasFocusLost

    public void atualizarListaMusicas(List<Musica> listaMusicas) {
        pnlListaMusicas.removeAll();

        for (Musica musica : listaMusicas) {
            MusicaItemPanel item = new MusicaItemPanel(musica);            

            pnlListaMusicas.add(item);
        }

        pnlListaMusicas.revalidate();
        pnlListaMusicas.repaint();
    }

    public JTextField getTxtBuscarMusicas() {
        return txtBuscarMusicas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMusicas;
    private javax.swing.JPanel pnlListaMusicas;
    private javax.swing.JScrollPane pnlResultadosBusca;
    private javax.swing.JPanel pnlSuperiorBusca;
    private javax.swing.JTextField txtBuscarMusicas;
    // End of variables declaration//GEN-END:variables
}
