/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spotifei.view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import spotifei.controller.CadastroController;

/**
 * Janela responsável pela interface gráfica de cadastro de usuários.
 * 
 * Esta tela permite que novos usuários sejam registrados no sistema.
 * A lógica de cadastro é delegada ao {@link CadastroController}.
 */
public class CadastroFrame extends javax.swing.JFrame {

    private CadastroController controller;
    
    /**
     * Construtor da tela de cadastro.
     * Inicializa os componentes visuais e instancia o controlador responsável.
     */
    public CadastroFrame() {
        initComponents();
        controller = new CadastroController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuarioCadastro = new javax.swing.JTextField();
        lblUsuarioCadastro = new javax.swing.JLabel();
        lblSenhaCadastro = new javax.swing.JLabel();
        txtNomeCadastro = new javax.swing.JTextField();
        lblNomeCadastro = new javax.swing.JLabel();
        btnCadastrarCadastro = new javax.swing.JButton();
        pswSenhaCadastro = new javax.swing.JPasswordField();
        btnLoginCadastro = new javax.swing.JButton();
        lblSpotifeiCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Spotifei");
        setName("Cadastro Spotifei"); // NOI18N

        txtUsuarioCadastro.setToolTipText("");

        lblUsuarioCadastro.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblUsuarioCadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuarioCadastro.setText("Usuário:");

        lblSenhaCadastro.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblSenhaCadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSenhaCadastro.setText("Senha:");

        txtNomeCadastro.setToolTipText("");

        lblNomeCadastro.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblNomeCadastro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeCadastro.setText("Nome:");

        btnCadastrarCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastrarCadastro.setText("Cadastrar-se");
        btnCadastrarCadastro.setBorderPainted(false);
        btnCadastrarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCadastroActionPerformed(evt);
            }
        });

        btnLoginCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLoginCadastro.setText("Login");
        btnLoginCadastro.setBorderPainted(false);
        btnLoginCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginCadastroActionPerformed(evt);
            }
        });

        lblSpotifeiCadastro.setBackground(new java.awt.Color(0, 0, 0));
        lblSpotifeiCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSpotifeiCadastro.setForeground(new java.awt.Color(0, 153, 0));
        lblSpotifeiCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/spotifeiLogo.png"));
        Image img = icon.getImage().getScaledInstance(120, 40, Image.SCALE_SMOOTH);
        lblSpotifeiCadastro.setIcon(new ImageIcon(img));
        lblSpotifeiCadastro.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSpotifeiCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pswSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnLoginCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pswSenhaCadastro, txtNomeCadastro, txtUsuarioCadastro});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblNomeCadastro, lblSenhaCadastro, lblUsuarioCadastro});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSpotifeiCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswSenhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginCadastro)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pswSenhaCadastro, txtNomeCadastro, txtUsuarioCadastro});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblNomeCadastro, lblSenhaCadastro, lblUsuarioCadastro});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCadastrarCadastro, btnLoginCadastro});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento acionado ao clicar no botão "Cadastrar".
     * Aciona o método do controlador para realizar o cadastro do usuário.
     * 
     * @param evt evento de clique do botão
     */
    private void btnCadastrarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCadastroActionPerformed
        // TODO add your handling code here:
        controller.cadastrarUsuario();
    }//GEN-LAST:event_btnCadastrarCadastroActionPerformed

    /**
     * Ação executada ao clicar no botão "Login".
     * 
     * Abre a janela de login de usuário e fecha a janela atual de cadastro.
     *
     * @param evt evento de clique no botão "Login"
     */
    private void btnLoginCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginCadastroActionPerformed
        // TODO add your handling code here:
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLoginCadastroActionPerformed
    
    public JTextField getTxtNomeCadastro() {
        return txtNomeCadastro;
    }

    public JPasswordField getPswSenhaCadastro() {
        return pswSenhaCadastro;
    }

    public JTextField getTxtUsuarioCadastro() {
        return txtUsuarioCadastro;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCadastro;
    private javax.swing.JButton btnLoginCadastro;
    private javax.swing.JLabel lblNomeCadastro;
    private javax.swing.JLabel lblSenhaCadastro;
    private javax.swing.JLabel lblSpotifeiCadastro;
    private javax.swing.JLabel lblUsuarioCadastro;
    private javax.swing.JPasswordField pswSenhaCadastro;
    private javax.swing.JTextField txtNomeCadastro;
    private javax.swing.JTextField txtUsuarioCadastro;
    // End of variables declaration//GEN-END:variables
}
