/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotifei.view;

import javax.swing.JLabel;
import spotifei.model.Musica;
import spotifei.model.Playlist;

/**
 *
 * @author adone
 */
public class ExibirPlaylistPanel extends javax.swing.JPanel {

    private Playlist playlist;
    
    public ExibirPlaylistPanel(Playlist playlist) {
        this.playlist = playlist;
        initComponents();
        lblTituloPlaylist.setText(playlist.getNome());
        listarMusicasPlaylist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloPlaylist = new javax.swing.JPanel();
        lblTituloPlaylist = new javax.swing.JLabel();
        pnlExibirMusicasPlaylist = new javax.swing.JScrollPane();
        pnlListaMusicasPlaylist = new javax.swing.JPanel();

        setBackground(new java.awt.Color(44, 44, 44));
        setMinimumSize(new java.awt.Dimension(850, 768));
        setPreferredSize(new java.awt.Dimension(850, 768));
        setLayout(new java.awt.BorderLayout());

        pnlTituloPlaylist.setBackground(new java.awt.Color(44, 44, 44));
        pnlTituloPlaylist.setPreferredSize(new java.awt.Dimension(850, 50));
        pnlTituloPlaylist.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 7));

        lblTituloPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloPlaylist.setText("Titulo da Playlist");
        pnlTituloPlaylist.add(lblTituloPlaylist);

        add(pnlTituloPlaylist, java.awt.BorderLayout.PAGE_START);

        pnlExibirMusicasPlaylist.setBackground(new java.awt.Color(55, 55, 55));

        pnlListaMusicasPlaylist.setBackground(new java.awt.Color(55, 55, 55));
        pnlListaMusicasPlaylist.setLayout(new javax.swing.BoxLayout(pnlListaMusicasPlaylist, javax.swing.BoxLayout.Y_AXIS));
        pnlExibirMusicasPlaylist.setViewportView(pnlListaMusicasPlaylist);

        add(pnlExibirMusicasPlaylist, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void listarMusicasPlaylist() {
        pnlListaMusicasPlaylist.removeAll();        
        
        for (Musica musica : playlist.getMusicas()) {
            MusicaItemPanel item = new MusicaItemPanel();
            item.getLblMusicaInfo().setText(musica.getTitulo() + " - " + musica.getArtista().getNome() + " (" + musica.getDuracao() + ")");
            
            pnlListaMusicasPlaylist.add(item);
        }

        pnlListaMusicasPlaylist.revalidate();
        pnlListaMusicasPlaylist.repaint();
    }

    public JLabel getLblTituloPlaylist() {
        return lblTituloPlaylist;
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTituloPlaylist;
    private javax.swing.JScrollPane pnlExibirMusicasPlaylist;
    private javax.swing.JPanel pnlListaMusicasPlaylist;
    private javax.swing.JPanel pnlTituloPlaylist;
    // End of variables declaration//GEN-END:variables
}
