/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotifei.view;

import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import spotifei.controller.PlaylistController;
import spotifei.controller.MainFrameController;
import spotifei.model.Musica;
import spotifei.model.Playlist;

/**
 *
 * @author adone
 */
public class ExibirPlaylistPanel extends javax.swing.JPanel {

    private Playlist playlist;
    private MainFrameController frameController;
    private PlaylistController playlistController;
    
    public ExibirPlaylistPanel(MainFrameController frameController, PlaylistController playlistController, Playlist playlist) {
        initComponents();
        this.playlist = playlist;
        this.frameController = frameController;
        this.playlistController = playlistController;
        lblTituloPlaylist.setText(playlist.getNome());
        listarMusicasPlaylist(playlistController.buscarMusicasPlaylist(playlist));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloPlaylist = new javax.swing.JPanel();
        lblTituloPlaylist = new javax.swing.JLabel();
        pnlExibirMusicasPlaylist = new javax.swing.JScrollPane();
        pnlListaMusicasPlaylist = new javax.swing.JPanel();
        pnlBotoesPlaylists = new javax.swing.JPanel();
        btnEditarPlaylist = new javax.swing.JButton();
        btnExcluirPlaylist = new javax.swing.JButton();
        btnRemoverMusicaPlaylist = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 44, 44));
        setMinimumSize(new java.awt.Dimension(850, 768));
        setPreferredSize(new java.awt.Dimension(850, 768));
        setLayout(new java.awt.BorderLayout());

        pnlTituloPlaylist.setBackground(new java.awt.Color(44, 44, 44));
        pnlTituloPlaylist.setPreferredSize(new java.awt.Dimension(850, 50));
        pnlTituloPlaylist.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 7));

        lblTituloPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloPlaylist.setText("Titulo da Playlist");
        pnlTituloPlaylist.add(lblTituloPlaylist);

        add(pnlTituloPlaylist, java.awt.BorderLayout.PAGE_START);

        pnlExibirMusicasPlaylist.setBackground(new java.awt.Color(55, 55, 55));

        pnlListaMusicasPlaylist.setBackground(new java.awt.Color(55, 55, 55));
        pnlListaMusicasPlaylist.setLayout(new javax.swing.BoxLayout(pnlListaMusicasPlaylist, javax.swing.BoxLayout.Y_AXIS));
        pnlExibirMusicasPlaylist.setViewportView(pnlListaMusicasPlaylist);

        add(pnlExibirMusicasPlaylist, java.awt.BorderLayout.CENTER);

        pnlBotoesPlaylists.setBackground(new java.awt.Color(44, 44, 44));
        pnlBotoesPlaylists.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 14));

        btnEditarPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarPlaylist.setText("Editar");
        btnEditarPlaylist.setBorderPainted(false);
        btnEditarPlaylist.setMaximumSize(new java.awt.Dimension(130, 40));
        btnEditarPlaylist.setMinimumSize(new java.awt.Dimension(130, 40));
        btnEditarPlaylist.setPreferredSize(new java.awt.Dimension(130, 40));
        btnEditarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPlaylistActionPerformed(evt);
            }
        });
        pnlBotoesPlaylists.add(btnEditarPlaylist);

        btnExcluirPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExcluirPlaylist.setText("Excluir");
        btnExcluirPlaylist.setBorderPainted(false);
        btnExcluirPlaylist.setMaximumSize(new java.awt.Dimension(130, 40));
        btnExcluirPlaylist.setMinimumSize(new java.awt.Dimension(130, 40));
        btnExcluirPlaylist.setPreferredSize(new java.awt.Dimension(130, 40));
        btnExcluirPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPlaylistActionPerformed(evt);
            }
        });
        pnlBotoesPlaylists.add(btnExcluirPlaylist);

        btnRemoverMusicaPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRemoverMusicaPlaylist.setText("Remover Música");
        btnRemoverMusicaPlaylist.setBorderPainted(false);
        btnRemoverMusicaPlaylist.setMaximumSize(new java.awt.Dimension(160, 40));
        btnRemoverMusicaPlaylist.setMinimumSize(new java.awt.Dimension(160, 40));
        btnRemoverMusicaPlaylist.setPreferredSize(new java.awt.Dimension(160, 40));
        btnRemoverMusicaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverMusicaPlaylistActionPerformed(evt);
            }
        });
        pnlBotoesPlaylists.add(btnRemoverMusicaPlaylist);

        add(pnlBotoesPlaylists, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPlaylistActionPerformed
        String novoNome = JOptionPane.showInputDialog(null, "Novo nome para a playlist: ", "Editar Playlist", JOptionPane.QUESTION_MESSAGE);
        
        if (novoNome != null) {
            if (!novoNome.trim().isEmpty()) {
                if (playlistController.renomearPlaylist(playlist.getId(), novoNome)) {
                    playlist.setNome(novoNome);
                    lblTituloPlaylist.setText(novoNome);
                    JOptionPane.showMessageDialog(null, "Playlist renomeada.", "Editar Playlist", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Preencha o campo de novo nome para Playlist.", "Aviso", JOptionPane.WARNING_MESSAGE);
            } 
        }
    }//GEN-LAST:event_btnEditarPlaylistActionPerformed

    private void btnExcluirPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPlaylistActionPerformed
        int confirmar = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a playlist?", "Excluir Playlist", JOptionPane.YES_NO_OPTION);
        
        if (confirmar == JOptionPane.YES_OPTION) {
            playlistController.excluirPlaylist(playlist);
            JOptionPane.showMessageDialog(null, "Playlist excluída.", "Excluir Playlist", JOptionPane.INFORMATION_MESSAGE);
            frameController.navegarPlaylists();
        }
    }//GEN-LAST:event_btnExcluirPlaylistActionPerformed

    private void btnRemoverMusicaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverMusicaPlaylistActionPerformed
        
        List<Musica> musicasPlaylist = playlistController.buscarMusicasPlaylist(playlist);
        
        JComboBox<Musica> comboBoxMusicas = new JComboBox<>();
        for (Musica musica : musicasPlaylist) {
            comboBoxMusicas.addItem(musica);
        }
        
        int confirmar = JOptionPane.showConfirmDialog(null, comboBoxMusicas, "Remover da Playlist", JOptionPane.OK_CANCEL_OPTION);
        
        if (confirmar == JOptionPane.OK_OPTION) {
            Musica musicaSelecionada = (Musica) comboBoxMusicas.getSelectedItem();
            playlistController.removerMusica(playlist, musicaSelecionada);
            JOptionPane.showMessageDialog(null, "Música removida.", "Remover da Playlist", JOptionPane.INFORMATION_MESSAGE);
            frameController.exibirPlaylist(playlist);
        }
    }//GEN-LAST:event_btnRemoverMusicaPlaylistActionPerformed

    public void listarMusicasPlaylist(List<Musica> listaMusicas) {
        pnlListaMusicasPlaylist.removeAll();        
        
        for (Musica musica : listaMusicas) {
            MusicaItemPanel item = new MusicaItemPanel(musica);
            
            pnlListaMusicasPlaylist.add(item);
        }

        pnlListaMusicasPlaylist.revalidate();
        pnlListaMusicasPlaylist.repaint();
    }

    public JLabel getLblTituloPlaylist() {
        return lblTituloPlaylist;
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarPlaylist;
    private javax.swing.JButton btnExcluirPlaylist;
    private javax.swing.JButton btnRemoverMusicaPlaylist;
    private javax.swing.JLabel lblTituloPlaylist;
    private javax.swing.JPanel pnlBotoesPlaylists;
    private javax.swing.JScrollPane pnlExibirMusicasPlaylist;
    private javax.swing.JPanel pnlListaMusicasPlaylist;
    private javax.swing.JPanel pnlTituloPlaylist;
    // End of variables declaration//GEN-END:variables
}
