/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotifei.view;

import java.util.List;
import javax.swing.JOptionPane;
import spotifei.app.Sessao;
import spotifei.controller.SpotifeiFrameController;
import spotifei.model.Playlist;

/**
 *
 * @author adone
 */
public class GerenciarPlaylistsPanel extends javax.swing.JPanel {

    private SpotifeiFrameController controller;
    
    public GerenciarPlaylistsPanel(SpotifeiFrameController controller) {
        initComponents();
        this.controller = controller;
        listarPlaylists(controller.buscarPlaylistsUsuario(Sessao.getUsuarioLogado()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperior = new javax.swing.JPanel();
        lblSuperiorPlaylists = new javax.swing.JLabel();
        pnlExibirPlaylists = new javax.swing.JScrollPane();
        pnlListaPlaylists = new javax.swing.JPanel();
        pnlBotoesPlaylists = new javax.swing.JPanel();
        btnCriarPlaylist = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 44, 44));
        setMinimumSize(new java.awt.Dimension(850, 768));
        setPreferredSize(new java.awt.Dimension(850, 768));
        setLayout(new java.awt.BorderLayout());

        pnlSuperior.setBackground(new java.awt.Color(44, 44, 44));
        pnlSuperior.setPreferredSize(new java.awt.Dimension(850, 50));
        pnlSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 7));

        lblSuperiorPlaylists.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblSuperiorPlaylists.setText("Suas Playlists");
        pnlSuperior.add(lblSuperiorPlaylists);

        add(pnlSuperior, java.awt.BorderLayout.PAGE_START);

        pnlExibirPlaylists.setBackground(new java.awt.Color(55, 55, 55));

        pnlListaPlaylists.setBackground(new java.awt.Color(55, 55, 55));
        pnlListaPlaylists.setLayout(new javax.swing.BoxLayout(pnlListaPlaylists, javax.swing.BoxLayout.Y_AXIS));
        pnlExibirPlaylists.setViewportView(pnlListaPlaylists);

        add(pnlExibirPlaylists, java.awt.BorderLayout.CENTER);

        pnlBotoesPlaylists.setBackground(new java.awt.Color(44, 44, 44));
        pnlBotoesPlaylists.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 14));

        btnCriarPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCriarPlaylist.setText("Nova Playlist");
        btnCriarPlaylist.setBorderPainted(false);
        btnCriarPlaylist.setMaximumSize(new java.awt.Dimension(160, 40));
        btnCriarPlaylist.setMinimumSize(new java.awt.Dimension(160, 40));
        btnCriarPlaylist.setPreferredSize(new java.awt.Dimension(160, 40));
        btnCriarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarPlaylistActionPerformed(evt);
            }
        });
        pnlBotoesPlaylists.add(btnCriarPlaylist);

        add(pnlBotoesPlaylists, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarPlaylistActionPerformed
        // TODO add your handling code here:
        String nomeNovaPlaylist = JOptionPane.showInputDialog(null, "Nome para a nova playlist: ", "Criar Playlist", JOptionPane.QUESTION_MESSAGE); // ALTERAR O THIS TALVEZ
        
        if (nomeNovaPlaylist != null && !nomeNovaPlaylist.trim().isEmpty()) {
            Playlist novaPlaylist = new Playlist(nomeNovaPlaylist, 0);
            
            if (controller.salvarPlaylist(novaPlaylist)) {
                adicionarPlaylist(novaPlaylist);
                pnlListaPlaylists.revalidate();
                pnlListaPlaylists.repaint();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha o campo de nome para Playlist.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCriarPlaylistActionPerformed

    public void adicionarPlaylist(Playlist playlist) {
        PlaylistItemPanel item = new PlaylistItemPanel(playlist);            

        item.setOnClick(() -> {
            controller.exibirPlaylist(playlist);
        });

        pnlListaPlaylists.add(item);
    }
    
    public void listarPlaylists(List<Playlist> listaPlaylists) {
        pnlListaPlaylists.removeAll();

        for (Playlist playlist : listaPlaylists) {
            adicionarPlaylist(playlist);
        }

        pnlListaPlaylists.revalidate();
        pnlListaPlaylists.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarPlaylist;
    private javax.swing.JLabel lblSuperiorPlaylists;
    private javax.swing.JPanel pnlBotoesPlaylists;
    private javax.swing.JScrollPane pnlExibirPlaylists;
    private javax.swing.JPanel pnlListaPlaylists;
    private javax.swing.JPanel pnlSuperior;
    // End of variables declaration//GEN-END:variables
}
