/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spotifei.view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import spotifei.controller.LoginController;

/**
 * Janela responsável pela interface de login do sistema.
 * 
 * Permite que o usuário entre com suas credenciais e acesse o sistema.
 * Também oferece a opção de navegar para a tela de cadastro.
 */
public class LoginFrame extends javax.swing.JFrame {

    private LoginController controller;
    
     /**
     * Construtor da janela de login.
     *
     * Inicializa os componentes gráficos e instancia o controlador responsável
     * pelas ações da tela.
     */
    public LoginFrame() {
        initComponents();        
        controller = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogarLogin = new javax.swing.JButton();
        txtUsuarioLogin = new javax.swing.JTextField();
        lblUsuarioLogin = new javax.swing.JLabel();
        lblSenhaLogin = new javax.swing.JLabel();
        lblSpotifeiLogin = new javax.swing.JLabel();
        btnCadastroLogin = new javax.swing.JButton();
        pswSenhaLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Spotifei");
        setSize(new java.awt.Dimension(465, 369));

        btnLogarLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogarLogin.setText("Logar");
        btnLogarLogin.setBorderPainted(false);
        btnLogarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarLoginActionPerformed(evt);
            }
        });

        txtUsuarioLogin.setToolTipText("");

        lblUsuarioLogin.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblUsuarioLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuarioLogin.setText("Usuario:");

        lblSenhaLogin.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblSenhaLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSenhaLogin.setText("Senha:");

        lblSpotifeiLogin.setBackground(new java.awt.Color(0, 0, 0));
        lblSpotifeiLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSpotifeiLogin.setForeground(new java.awt.Color(0, 153, 0));
        lblSpotifeiLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/spotifeiLogo.png"));
        Image img = icon.getImage().getScaledInstance(120, 40, Image.SCALE_SMOOTH);
        lblSpotifeiLogin.setIcon(new ImageIcon(img));
        lblSpotifeiLogin.setToolTipText("");

        btnCadastroLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastroLogin.setText("Cadastro");
        btnCadastroLogin.setBorderPainted(false);
        btnCadastroLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCadastroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSpotifeiLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pswSenhaLogin, txtUsuarioLogin});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblSenhaLogin, lblUsuarioLogin});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSpotifeiLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnLogarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCadastroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pswSenhaLogin, txtUsuarioLogin});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblSenhaLogin, lblUsuarioLogin});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCadastroLogin, btnLogarLogin});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação executada ao clicar no botão "Cadastro".
     * 
     * Abre a janela de cadastro de novo usuário e fecha a janela atual de login.
     *
     * @param evt evento de clique no botão "Cadastro"
     */
    private void btnCadastroLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroLoginActionPerformed
        // TODO add your handling code here:
        CadastroFrame cadastroFrame = new CadastroFrame();
        cadastroFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnCadastroLoginActionPerformed

    /**
     * Ação executada ao clicar no botão "Login".
     * 
     * Chama o método do controlador para realizar a autenticação
     * com os dados informados pelo usuário.
     *
     * @param evt evento de clique no botão "Entrar"
     */
    private void btnLogarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarLoginActionPerformed
        // TODO add your handling code here:
        controller.logarUsuario();
    }//GEN-LAST:event_btnLogarLoginActionPerformed

    public JPasswordField getPswSenhaLogin() {
        return pswSenhaLogin;
    }
    
    public JTextField getTxtUsuarioLogin() {
        return txtUsuarioLogin;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroLogin;
    private javax.swing.JButton btnLogarLogin;
    private javax.swing.JLabel lblSenhaLogin;
    private javax.swing.JLabel lblSpotifeiLogin;
    private javax.swing.JLabel lblUsuarioLogin;
    private javax.swing.JPasswordField pswSenhaLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
