/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spotifei.view;

import javax.swing.JTextField;
import spotifei.controller.LoginController;

/**
 *
 * @author unifacalen
 */
public class LoginFrame extends javax.swing.JFrame {

    private LoginController controller;
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        controller = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogarLogin = new javax.swing.JButton();
        txtUsuarioLogin = new javax.swing.JTextField();
        lblUsuarioLogin = new javax.swing.JLabel();
        txtSenhaLogin = new javax.swing.JTextField();
        lblSenhaLogin = new javax.swing.JLabel();
        lblSpotifeiLogin = new javax.swing.JLabel();
        btnCadastroLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Spotifei");
        setSize(new java.awt.Dimension(465, 369));

        btnLogarLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogarLogin.setText("Login");
        btnLogarLogin.setBorderPainted(false);
        btnLogarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarLoginActionPerformed(evt);
            }
        });

        txtUsuarioLogin.setToolTipText("");

        lblUsuarioLogin.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblUsuarioLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuarioLogin.setText("Usuario:");

        txtSenhaLogin.setToolTipText("");

        lblSenhaLogin.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblSenhaLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSenhaLogin.setText("Senha:");

        lblSpotifeiLogin.setBackground(new java.awt.Color(0, 0, 0));
        lblSpotifeiLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSpotifeiLogin.setForeground(new java.awt.Color(0, 153, 0));
        lblSpotifeiLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpotifeiLogin.setText("SPOTIFEI");
        lblSpotifeiLogin.setToolTipText("");

        btnCadastroLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCadastroLogin.setText("Cadastro");
        btnCadastroLogin.setBorderPainted(false);
        btnCadastroLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSpotifeiLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnCadastroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSpotifeiLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnCadastroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarLoginActionPerformed
        // TODO add your handling code here:
        controller.logarUsuario();
    }//GEN-LAST:event_btnLogarLoginActionPerformed

    private void btnCadastroLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroLoginActionPerformed
        // TODO add your handling code here:
        CadastroFrame cadastroFrame = new CadastroFrame();
        cadastroFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnCadastroLoginActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginFrame().setVisible(true);
//            }
//        });
//    }
    
    public JTextField getTxtSenhaLogin() {
        return txtSenhaLogin;
    }

    public void setTxtSenhaLogin(JTextField txtSenhaLogin) {
        this.txtSenhaLogin = txtSenhaLogin;
    }

    public JTextField getTxtUsuarioLogin() {
        return txtUsuarioLogin;
    }

    public void setTxtUsuarioLogin(JTextField txtUsuarioLogin) {
        this.txtUsuarioLogin = txtUsuarioLogin;
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroLogin;
    private javax.swing.JButton btnLogarLogin;
    private javax.swing.JLabel lblSenhaLogin;
    private javax.swing.JLabel lblSpotifeiLogin;
    private javax.swing.JLabel lblUsuarioLogin;
    private javax.swing.JTextField txtSenhaLogin;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
