/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotifei.view;

import javax.swing.JLabel;
import spotifei.model.Musica;

/**
 *
 * @author adone
 */
public class MusicaItemPanel extends javax.swing.JPanel {
    
    public MusicaItemPanel(Musica musica) {
        initComponents();
        lblMusicaInfo.setText(musica.getTitulo() + " - " + musica.getArtista().getNome() + " (" + musica.getDuracao() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMusicaInfo = new javax.swing.JLabel();
        pnlBotoes = new javax.swing.JPanel();
        btnCurtir = new javax.swing.JButton();
        btnDescurtir = new javax.swing.JButton();
        btnAdicionarPlaylist = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 44, 44));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(2147483647, 70));
        setMinimumSize(new java.awt.Dimension(212, 70));
        setPreferredSize(new java.awt.Dimension(0, 70));
        setLayout(new java.awt.BorderLayout());

        lblMusicaInfo.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        lblMusicaInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMusicaInfo.setText("Música - Artista - (00:00)");
        add(lblMusicaInfo, java.awt.BorderLayout.CENTER);

        pnlBotoes.setBackground(new java.awt.Color(44, 44, 44));
        pnlBotoes.setLayout(new javax.swing.BoxLayout(pnlBotoes, javax.swing.BoxLayout.LINE_AXIS));

        btnCurtir.setText("Curtir");
        pnlBotoes.add(btnCurtir);

        btnDescurtir.setText("Descurtir");
        pnlBotoes.add(btnDescurtir);

        btnAdicionarPlaylist.setText("Add a Playlist");
        pnlBotoes.add(btnAdicionarPlaylist);

        add(pnlBotoes, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblMusicaInfo() {
        return lblMusicaInfo;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPlaylist;
    private javax.swing.JButton btnCurtir;
    private javax.swing.JButton btnDescurtir;
    private javax.swing.JLabel lblMusicaInfo;
    private javax.swing.JPanel pnlBotoes;
    // End of variables declaration//GEN-END:variables
}
