/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotifei.view;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import spotifei.app.Sessao;
import spotifei.controller.MusicaController;
import spotifei.controller.PlaylistController;
import spotifei.model.Musica;
import spotifei.model.Playlist;

/**
 * Painel responsável por exibir informações de uma música individual,
 * além de fornecer botões de interação como curtir, descurtir e adicionar a uma playlist.
 */
public class MusicaItemPanel extends javax.swing.JPanel {
    
    private Musica musica;
    
    /**
     * Construtor do painel da música.
     *
     * Inicializa os componentes gráficos e configura as informações da música exibida.
     *
     * @param musica a música que será representada por este painel
     */
    public MusicaItemPanel(Musica musica) {
        initComponents();
        this.musica = musica;
        lblMusicaInfo.setText(musica.getTitulo() + " - " + musica.getArtista().getNome() + " (" + musica.getDuracao() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMusicaInfo = new javax.swing.JLabel();
        pnlBotoes = new javax.swing.JPanel();
        btnCurtir = new javax.swing.JButton();
        btnDescurtir = new javax.swing.JButton();
        btnAdicionarPlaylist = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 44, 44));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(2147483647, 70));
        setMinimumSize(new java.awt.Dimension(212, 70));
        setPreferredSize(new java.awt.Dimension(0, 70));
        setLayout(new java.awt.BorderLayout());

        lblMusicaInfo.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        lblMusicaInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMusicaInfo.setText("Música - Artista - (00:00)");
        add(lblMusicaInfo, java.awt.BorderLayout.CENTER);

        pnlBotoes.setBackground(new java.awt.Color(44, 44, 44));
        pnlBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 13));

        btnCurtir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/likeIcon.png"))); // NOI18N
        btnCurtir.setToolTipText("Curtir");
        btnCurtir.setBorderPainted(false);
        btnCurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurtirActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnCurtir);

        btnDescurtir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dislikeIcon.png"))); // NOI18N
        btnDescurtir.setToolTipText("Descurtir");
        btnDescurtir.setBorderPainted(false);
        btnDescurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescurtirActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnDescurtir);

        btnAdicionarPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plusIcon.png"))); // NOI18N
        btnAdicionarPlaylist.setToolTipText("Adicionar na Playlist");
        btnAdicionarPlaylist.setBorderPainted(false);
        btnAdicionarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPlaylistActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnAdicionarPlaylist);

        add(pnlBotoes, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação executada ao clicar no botão "Add à Playlist".
     *
     * Exibe uma lista de playlists do usuário em um comboBox, permitindo escolher uma
     * para adicionar a música atual. Exibe um diálogo de confirmação.
     *
     * @param evt evento de clique no botão
     */
    private void btnAdicionarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPlaylistActionPerformed
        
        PlaylistController playlistController = new PlaylistController();
        List<Playlist> playlistsUsuario = playlistController.buscarPlaylistsUsuario(Sessao.getUsuarioLogado());
        
        JComboBox<Playlist> comboBoxPlaylists = new JComboBox<>();
        for (Playlist playlist : playlistsUsuario) {
            comboBoxPlaylists.addItem(playlist);
        }
        
        int confirmar = JOptionPane.showConfirmDialog(null, comboBoxPlaylists, "Adicionar na Playlist", JOptionPane.OK_CANCEL_OPTION);
        
        if (confirmar == JOptionPane.OK_OPTION) {
            Playlist playlistSelecionada = (Playlist) comboBoxPlaylists.getSelectedItem();
            if (playlistController.adicionarMusica(playlistSelecionada, musica)) {
                JOptionPane.showMessageDialog(null, "Música adicionada em " + playlistSelecionada, "Adicionar na Playlist", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAdicionarPlaylistActionPerformed

    /**
     * Ação executada ao clicar no botão "Curtir".
     *
     * Envia uma reação de curtida para a música exibida, associando-a ao usuário logado.
     * Exibe o retorno da ação em um diálogo.
     *
     * @param evt evento de clique no botão
     */
    private void btnCurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurtirActionPerformed
        
        MusicaController musicaController = new MusicaController();
        String mensagem = musicaController.reagirMusica(Sessao.getUsuarioLogado(), musica, 'C');
        
        if (mensagem != null) {
            JOptionPane.showMessageDialog(null, mensagem, "Curtir música", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnCurtirActionPerformed

    /**
     * Ação executada ao clicar no botão "Descurtir".
     *
     * Envia uma reação de descurtida para a música exibida, associando-a ao usuário logado.
     * Exibe o retorno da ação em um diálogo.
     *
     * @param evt evento de clique no botão
     */
    private void btnDescurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescurtirActionPerformed
        
        MusicaController musicaController = new MusicaController();
        String mensagem = musicaController.reagirMusica(Sessao.getUsuarioLogado(), musica, 'D');
        
        if (mensagem != null) {
            JOptionPane.showMessageDialog(null, mensagem, "Descurtir música", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDescurtirActionPerformed

    public JButton getBtnCurtir() {
        return btnCurtir;
    }

    public JButton getBtnDescurtir() {
        return btnDescurtir;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPlaylist;
    private javax.swing.JButton btnCurtir;
    private javax.swing.JButton btnDescurtir;
    private javax.swing.JLabel lblMusicaInfo;
    private javax.swing.JPanel pnlBotoes;
    // End of variables declaration//GEN-END:variables
}
