/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotifei.view;

import javax.swing.JLabel;

/**
 *
 * @author adone
 */
public class PlaylistItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlaylistItemPanel
     */
    public PlaylistItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPlaylistInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 44, 44));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMinimumSize(new java.awt.Dimension(0, 70));
        setPreferredSize(new java.awt.Dimension(0, 70));
        setLayout(new java.awt.BorderLayout());

        lblPlaylistInfo.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblPlaylistInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaylistInfo.setText("Playlist - Qnt. Músicas");
        add(lblPlaylistInfo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblPlaylistInfo() {
        return lblPlaylistInfo;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPlaylistInfo;
    // End of variables declaration//GEN-END:variables
}
