/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotifei.view;

import java.util.List;
import spotifei.app.Sessao;
import spotifei.model.Playlist;

/**
 *
 * @author adone
 */
public class PlaylistsPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlaylistsPanel
     */
    public PlaylistsPanel() {
        initComponents();
        atualizarListaPlaylists(Sessao.getUsuarioLogado().getPlaylists());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperior = new javax.swing.JPanel();
        lblTituloPlaylists = new javax.swing.JLabel();
        pnlExibirPlaylists = new javax.swing.JScrollPane();
        pnlListaPlaylists = new javax.swing.JPanel();
        pnlBotoesPlaylists = new javax.swing.JPanel();
        btnCriarPlaylist = new javax.swing.JButton();
        btnEditarPlaylist = new javax.swing.JButton();
        btnExcluirPlaylist = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 44, 44));
        setMinimumSize(new java.awt.Dimension(850, 768));
        setLayout(new java.awt.BorderLayout());

        pnlSuperior.setBackground(new java.awt.Color(44, 44, 44));
        pnlSuperior.setPreferredSize(new java.awt.Dimension(850, 50));
        pnlSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 7));

        lblTituloPlaylists.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloPlaylists.setText("Suas Playlists");
        pnlSuperior.add(lblTituloPlaylists);

        add(pnlSuperior, java.awt.BorderLayout.PAGE_START);

        pnlExibirPlaylists.setBackground(new java.awt.Color(55, 55, 55));

        pnlListaPlaylists.setBackground(new java.awt.Color(55, 55, 55));
        pnlListaPlaylists.setLayout(new javax.swing.BoxLayout(pnlListaPlaylists, javax.swing.BoxLayout.Y_AXIS));
        pnlExibirPlaylists.setViewportView(pnlListaPlaylists);

        add(pnlExibirPlaylists, java.awt.BorderLayout.CENTER);

        pnlBotoesPlaylists.setBackground(new java.awt.Color(44, 44, 44));
        pnlBotoesPlaylists.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 14));

        btnCriarPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCriarPlaylist.setText("Criar");
        btnCriarPlaylist.setBorderPainted(false);
        btnCriarPlaylist.setPreferredSize(new java.awt.Dimension(130, 40));
        pnlBotoesPlaylists.add(btnCriarPlaylist);

        btnEditarPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditarPlaylist.setText("Editar");
        btnEditarPlaylist.setBorderPainted(false);
        btnEditarPlaylist.setPreferredSize(new java.awt.Dimension(130, 40));
        pnlBotoesPlaylists.add(btnEditarPlaylist);

        btnExcluirPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExcluirPlaylist.setText("Excluir");
        btnExcluirPlaylist.setBorderPainted(false);
        btnExcluirPlaylist.setPreferredSize(new java.awt.Dimension(130, 40));
        pnlBotoesPlaylists.add(btnExcluirPlaylist);

        add(pnlBotoesPlaylists, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    public void atualizarListaPlaylists(List<Playlist> listaPlaylists) {
        pnlListaPlaylists.removeAll();

        for (Playlist playlist : listaPlaylists) {
            PlaylistItemPanel item = new PlaylistItemPanel();
            item.getLblPlaylistInfo().setText(playlist.getNome() + " - " + playlist.getMusicas().size() + "Música(s)");

            pnlListaPlaylists.add(item);
        }

        pnlListaPlaylists.revalidate();
        pnlListaPlaylists.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarPlaylist;
    private javax.swing.JButton btnEditarPlaylist;
    private javax.swing.JButton btnExcluirPlaylist;
    private javax.swing.JLabel lblTituloPlaylists;
    private javax.swing.JPanel pnlBotoesPlaylists;
    private javax.swing.JScrollPane pnlExibirPlaylists;
    private javax.swing.JPanel pnlListaPlaylists;
    private javax.swing.JPanel pnlSuperior;
    // End of variables declaration//GEN-END:variables
}
