/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotifei.view;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import spotifei.app.Sessao;
import spotifei.controller.PlaylistController;
import spotifei.model.Musica;
import spotifei.model.Playlist;

/**
 * Painel que representa visualmente uma música reagida pelo usuário.
 * Exibe informações da música e permite adicioná-la a uma playlist.
 */
public class ReacaoItemPanel extends javax.swing.JPanel {
    
    private Musica musica;
    
    /**
     * Construtor do painel que inicializa os componentes e exibe os dados da música.
     *
     * @param musica Objeto {@code Musica} que será exibido no painel.
     */
    public ReacaoItemPanel(Musica musica) {
        initComponents();
        this.musica = musica;
        lblMusicaInfo.setText(musica.getTitulo() + " - " + musica.getArtista().getNome() + " (" + musica.getDuracao() + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMusicaInfo = new javax.swing.JLabel();
        pnlBotoes = new javax.swing.JPanel();
        btnAdicionarPlaylist = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 44, 44));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(2147483647, 70));
        setMinimumSize(new java.awt.Dimension(212, 70));
        setPreferredSize(new java.awt.Dimension(0, 70));
        setLayout(new java.awt.BorderLayout());

        lblMusicaInfo.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        lblMusicaInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMusicaInfo.setText("Música - Artista - (00:00)");
        add(lblMusicaInfo, java.awt.BorderLayout.CENTER);

        pnlBotoes.setBackground(new java.awt.Color(44, 44, 44));
        pnlBotoes.setLayout(new javax.swing.BoxLayout(pnlBotoes, javax.swing.BoxLayout.LINE_AXIS));

        btnAdicionarPlaylist.setText("Add a Playlist");
        btnAdicionarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPlaylistActionPerformed(evt);
            }
        });
        pnlBotoes.add(btnAdicionarPlaylist);

        add(pnlBotoes, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação executada ao clicar no botão de adicionar a música a uma playlist.
     * Exibe uma lista com as playlists do usuário e adiciona a música à playlist selecionada.
     *
     * @param evt Evento de clique do botão.
     */
    private void btnAdicionarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPlaylistActionPerformed

        PlaylistController playlistController = new PlaylistController();
        List<Playlist> playlistsUsuario = playlistController.buscarPlaylistsUsuario(Sessao.getUsuarioLogado());

        JComboBox<Playlist> comboBoxPlaylists = new JComboBox<>();
        for (Playlist playlist : playlistsUsuario) {
            comboBoxPlaylists.addItem(playlist);
        }

        int confirmar = JOptionPane.showConfirmDialog(null, comboBoxPlaylists, "Adicionar na Playlist", JOptionPane.OK_CANCEL_OPTION);

        if (confirmar == JOptionPane.OK_OPTION) {
            Playlist playlistSelecionada = (Playlist) comboBoxPlaylists.getSelectedItem();
            if (playlistController.adicionarMusica(playlistSelecionada, musica)) {
                JOptionPane.showMessageDialog(null, "Música adicionada em " + playlistSelecionada, "Adicionar na Playlist", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAdicionarPlaylistActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPlaylist;
    private javax.swing.JLabel lblMusicaInfo;
    private javax.swing.JPanel pnlBotoes;
    // End of variables declaration//GEN-END:variables
}
