/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spotifei.view;

//import java.awt.CardLayout;
import javax.swing.JPanel;
import spotifei.controller.MainFrameController;

/**
 *
 * @author adone
 */
public class SpotifeiFrame extends javax.swing.JFrame {
    
    private MainFrameController controller;
    
    public SpotifeiFrame() {
        initComponents();
        controller = new MainFrameController(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavegacaoSpotifei = new javax.swing.JPanel();
        lblSpotifeiSpotifei = new javax.swing.JLabel();
        btnPlaylistNavegacao = new javax.swing.JButton();
        btnMusicasNavegacao = new javax.swing.JButton();
        pnlMainSpotifei = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));

        pnlNavegacaoSpotifei.setBackground(new java.awt.Color(30, 30, 30));

        lblSpotifeiSpotifei.setBackground(new java.awt.Color(0, 0, 0));
        lblSpotifeiSpotifei.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSpotifeiSpotifei.setForeground(new java.awt.Color(0, 153, 0));
        lblSpotifeiSpotifei.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpotifeiSpotifei.setText("SPOTIFEI");
        lblSpotifeiSpotifei.setToolTipText("");

        btnPlaylistNavegacao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPlaylistNavegacao.setText("Playlists");
        btnPlaylistNavegacao.setBorderPainted(false);
        btnPlaylistNavegacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaylistNavegacaoActionPerformed(evt);
            }
        });

        btnMusicasNavegacao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnMusicasNavegacao.setText("Músicas");
        btnMusicasNavegacao.setBorderPainted(false);
        btnMusicasNavegacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicasNavegacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNavegacaoSpotifeiLayout = new javax.swing.GroupLayout(pnlNavegacaoSpotifei);
        pnlNavegacaoSpotifei.setLayout(pnlNavegacaoSpotifeiLayout);
        pnlNavegacaoSpotifeiLayout.setHorizontalGroup(
            pnlNavegacaoSpotifeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavegacaoSpotifeiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlNavegacaoSpotifeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSpotifeiSpotifei, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(btnPlaylistNavegacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMusicasNavegacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlNavegacaoSpotifeiLayout.setVerticalGroup(
            pnlNavegacaoSpotifeiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavegacaoSpotifeiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSpotifeiSpotifei, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(btnMusicasNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnPlaylistNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMainSpotifei.setBackground(new java.awt.Color(44, 44, 44));
        pnlMainSpotifei.setMinimumSize(new java.awt.Dimension(850, 768));
        pnlMainSpotifei.setPreferredSize(new java.awt.Dimension(850, 768));
        pnlMainSpotifei.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNavegacaoSpotifei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMainSpotifei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavegacaoSpotifei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMainSpotifei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMusicasNavegacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicasNavegacaoActionPerformed
        controller.navegarMusicas();
    }//GEN-LAST:event_btnMusicasNavegacaoActionPerformed

    private void btnPlaylistNavegacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaylistNavegacaoActionPerformed
        controller.navegarPlaylists();
    }//GEN-LAST:event_btnPlaylistNavegacaoActionPerformed

    public JPanel getPnlMainSpotifei() {
        return pnlMainSpotifei;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMusicasNavegacao;
    private javax.swing.JButton btnPlaylistNavegacao;
    private javax.swing.JLabel lblSpotifeiSpotifei;
    private javax.swing.JPanel pnlMainSpotifei;
    private javax.swing.JPanel pnlNavegacaoSpotifei;
    // End of variables declaration//GEN-END:variables
}
